### ISSUE TITLE
Settings Toggles not working correctly

### ISSUE THREAD

**Issue by christophdb** [seatable/seatable-plugin-table-relationship#49]
This has worked before:

Settings has four toogles:
- Show linked record relationship: OK
- show lookup relationship: NOTHING HAPPENS
- show 2nd level lookup relationship: toggles the "lookup relationship"
- show tables without links: OK

![image](https://github.com/seatable/seatable-plugin-table-relationships/assets/7803347/a3b77aa1-5f76-48b2-9c9e-39d3ce2fdd2d)

**Comment by matteobu** [comment]
https://github.com/user-attachments/assets/92b940f8-d640-4d1f-aa4b-0557cac71e9c
